### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by DaniMorales97** [Priyansh61/Space-Fighters#1]
I saw your repository exploring for an open source project that used pygame. My intention is to help you with this project as well as help others with theirs and continue learning along the way. For now, I forked your repo and I'll be adding commits to it. When I feel like I did substantial changes I will make a pull request. I already tried your game and it's nice. However, I think together we can improve it and learn from each other while at it.

I hope you are okay with me helping,
Cheers.

**Comment by Priyansh61** [comment]
@DaniMorales97 glad that you enjoyed the game and i hope that we both get to learn something from one another by contributing on this project.

It would be great to work along you and incase if you get stuck somewhere feel free to ask.

**Comment by DaniMorales97** [comment]
Great, thanks
